version: '2'

services:
  app:
    # image: 'scientistroom-backend:0.1'
    image: notmiddev30/scientistroom:1.2
    # build:
    #   context: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sci-room

  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "batmaaanpls@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "kevindurant35!"
  #   ports:
  #     - "16543:80"
  #   depends_on:
  #     - db